version: '3.8'

services:
  redis:
    image: redis:latest
    command: >
      sh -c "redis-server --requirepass $$(cat /run/secrets/redis_password) --appendonly yes"
    secrets:
      - redis_password
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"

  web:
    image: mbc-web-app:1.0.1
    ports:
      - "4001:4000"
    depends_on:
      - redis
    secrets:
      - redis_password
    command: >
      sh -c "REDIS_PASSWORD=$$(cat /run/secrets/redis_password) &&
             REDIS_URL=redis://default:$$REDIS_PASSWORD@redis:6379 npm start"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  redis_data:

secrets:
  redis_password:
    file: ./secret-pass.txt
