version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server-mbc-web
    command: redis-server --requirepass Admin123 --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mbc-web-app
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://default:Admin123@redis:6379
    command: npm start

volumes:
  redis_data:
